const catsData = [
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "images/angry.jpeg",
        // image: "https://i.postimg.cc/nzrbZvyt/angry.jpg",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody", "insomniac"],
        isGif: false,
        image: "images/angry2.jpeg",
        // image: "https://i.postimg.cc/8CtQqynH/angry2.jpg",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "images/angry3.jpeg",
        // image: "https://i.postimg.cc/bJqtCvSM/angry3.jpg",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["confused", "sad"],
        isGif: false,
        image: "images/confused.jpeg",
        // image: "https://i.postimg.cc/50pFZMwt/confused.jpg",
        alt: "A cat looking confused",
    },
    {
        emotionTags: ["dominant", "moody"],
        isGif: false,
        image: "images/dominant.jpeg",
        // image: "https://i.postimg.cc/ZY7dH4b7/dominant.jpg",
        alt: "A cat looking dominant",
    },
    {
        emotionTags: ["happy", "relaxed"],
        isGif: false,
        image: "images/happy.jpeg",
        // image: "https://i.postimg.cc/VkM0ztjp/happy.jpg",
        alt: "A cat looking happy",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "images/hungry.jpeg",
        // image: "https://i.postimg.cc/s24BhRHJ/hungry.jpg",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "images/hungry1.jpeg",
        // image: "https://i.postimg.cc/Qt6HfJ39/hungry1.jpg",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "images/insomnia.jpeg",
        // image: "https://i.postimg.cc/4ymnqHf8/insomnia.jpg",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "images/insomnia1.jpeg",
        // image: "https://i.postimg.cc/wxG1J22n/insomnia1.jpg",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: false,
        image: "images/lazy.jpeg",
        // image: "https://i.postimg.cc/K8X4pYdN/lazy.jpg",
        alt: "A cat looking lazy",
    },
    {
        emotionTags: ["scared"],
        isGif: false,
        image: "images/nervous.jpeg",
        // image: "https://i.postimg.cc/xdn8Y4jN/nervous.jpg",
        alt: "A cat looking nervous",
    },
    {
        emotionTags: ["sad"],
        isGif: false,
        image: "images/sad.jpeg",
        // image: "https://i.postimg.cc/k5JJLRwx/sad.jpg",
        alt: "A cat looking sad",
    },
    {
        emotionTags: ["sad", "moody"],
        isGif: false,
        image: "images/sad1.jpeg",
        // image: "https://i.postimg.cc/gJrY29Cj/sad1.jpg",
        alt: "A cat looking sad",
    },
    {
        emotionTags: ["sleepy"],
        isGif: false,
        image: "images/sleepy.jpeg",
        // image: "https://i.postimg.cc/Ss5mXT4r/sleepy.jpg",
        alt: "A cat looking sleepy",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "images/angry.gif",
        // image: "https://i.postimg.cc/8c0fzBXQ/angry.gif",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "images/angry2.gif",
        // image: "https://i.postimg.cc/3NRDhbBF/angry2.gif",
        alt: "A cat looking angry",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "images/confused2.gif",
        // image: "https://i.postimg.cc/43g7y3Pd/confused2.gif",
        alt: "A cat looking confused",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "images/dominant.gif",
        // image: "https://i.postimg.cc/FswJtpJ0/dominant.gif",
        alt: "A cat looking dominant",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "images/happy.gif",
        // image: "https://i.postimg.cc/pTVmQ1gM/happy.gif",
        alt: "A cat looking happy",
    },
    {
        emotionTags: ["hungry", "sad", "confused"],
        isGif: true,
        image: "images/confused.gif",
        // image: "https://i.postimg.cc/VLJbHp5Y/confused.gif",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "images/hungry.gif",
        // image: "https://i.postimg.cc/j2mCbqCR/hungry.gif",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "images/hungry2.gif",
        // image: "https://i.postimg.cc/5NQ6mzky/hungry2.gif",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["insomniac", "scared"],
        isGif: true,
        image: "images/insomnia.gif",
        // image: "https://i.postimg.cc/76LLJJ2x/insomnia.gif",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["insomniac", "scared"],
        isGif: true,
        image: "images/insomnia2.gif",
        // image: "https://i.postimg.cc/0NnQN0rW/insomnia2.gif",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "images/lazy.gif",
        // image: "https://i.postimg.cc/x1K8w2QS/lazy.gif",
        alt: "A cat looking relaxed",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "images/relaxed2.gif",
        // image: "https://i.postimg.cc/8zBkymdp/relaxed2.gif",
        alt: "A cat looking relaxed",
    },
    {
        emotionTags: ["scared", "sad"],
        isGif: true,
        image: "images/nervous.gif",
        // image: "https://i.postimg.cc/wMmgDXTd/nervous.gif",
        alt: "A cat looking nervous",
    },
    {
        emotionTags: ["scared"],
        isGif: true,
        image: "images/nervous2.gif",
        // image: "https://i.postimg.cc/grbdsxnL/nervous2.gif",
        alt: "A cat looking scared",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "images/sad.gif",
        // image: "https://i.postimg.cc/3wt8hrbz/sad.gif",
        alt: "A cat looking sad",
    },
]